export { default as happy } from './happy.png'
export { default as indifferent } from './indifferent.png'
export { default as sad } from './sad.png'
export { default as veryhappy } from './veryhappy.png'
export { default as verysad } from './verysad.png'
export { default as depressed } from './depressed.png'
export { default as angry } from './angry.png'
export { default as laugh } from './laugh.png'
